require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

# Polyfill for Expo Modules Core expecting `get_folly_config` on older RN (<=0.73)
# RN 0.73 exposes `folly_flags` but not `get_folly_config`.
# Define a minimal shim so ExpoModulesCore.podspec can compute compiler flags.
unless respond_to?(:get_folly_config)
  def get_folly_config()
    { compiler_flags: folly_flags() }
  end
end

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

use_modular_headers!

plugin 'cocoapods-patch'

def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

setup_permissions([
  # 'AppTrackingTransparency',
  # 'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  # 'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  # 'MediaLibrary',
  # 'Microphone',
  # 'Motion',
  'Notifications',
  # 'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])

def all_pods
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson', modular_headers: true
  $RNFirebaseAnalyticsWithoutAdIdSupport = true

  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    # :flipper_configuration => flipper_config
  )

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

abstract_target 'defaults' do

  all_pods

  target 'RocketChatRN' # Experimental app
  target 'Rocket.Chat' # Official app
  target 'NotificationService'
end

$static_framework = [
  'WatermelonDB',
  'simdjson',
]
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
        Pod::BuildType.static_library # >= 1.9
      end
    end
  end
end


config = use_native_modules!
post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    # :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      case target.name
      when 'RCT-Folly'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      else
        config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      end
    end
  end

  bitcode_strip_path = `xcrun --find bitcode_strip`.strip
  Dir["Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/**/OpenSSL.framework/OpenSSL"].each do |bin|
    puts "Stripping bitcode: #{bin}"
    system("#{bitcode_strip_path} -r \"#{bin}\" -o \"#{bin}\"")
  end
end
